version : '3'

services:
  weather_forecast_api:
    image: weather_forecast_api
    ports:
      - 4000:5000
    volumes:
      - log_location:/var/log
    networks:
      - weather_forecast_network
  
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - weather_forecast_network
  
  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - log_location:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - weather_forecast_network

  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - weather_forecast_network
  
  grafana:
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - weather_forecast_network

networks:
  weather_forecast_network:
    
volumes:
  log_location: