server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - match:
          pipeline_name: "security"
          selector: '{app="api"}'
          stages:
            - regex:
                expression: '(?P<email>([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+))'
            - template:
                source: email
                template: '{{ if not (empty .Value) }} true {{ end }}'
            - regex:
                # this regex matches any 16 digits may need to update.
                expression: '(?P<creditcard>(?:\d[ -]*?){13,16})'
            - template:
                source: creditcard
                template: '{{ if not (empty .Value) }} true {{ end }}'
            - regex:
                expression: '(?P<phone>(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4})'
            - template:
                source: phone
                template: '{{ if not (empty .Value) }} true {{ end }}'
            - template:
                source: sensitive
                template: '{{ or .email .creditcard .phone false }}'
            - labels:
                sensitive:
    
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*local.log
          app: 'api'